### PR TITLE
Relax upper bound for futures dependency

### PR DESCRIPTION
**Pull request by aaltay**
This would make it easier for its users to use latest version of futures.

### CODE REVIEW

**Review by lowaa — APPROVED** [review]
lgtm!

**Comment by lowaa** [comment]
thanks for the pr!

**Comment by aaltay** [comment]
Thank you!

**Comment by lukecwik** [comment]
Would you mind performing a release of collapsing-thread-pool-executor to PyPi that includes this change?

**Comment by aaltay** [comment]
@lowaa if you prefer to add one of us as a maintainer. I will be happy to do the release.

**Comment by lowaa** [comment]
@lukecwik @aaltay 

Sorry guys, the owner of the pypi project is on holiday for 2 weeks. When we can get in contact with him again we'll do the release.

**Comment by lukecwik** [comment]
Thanks for the info and we will wait.

**Comment by lukecwik** [comment]
Any updates on getting a release?

**Comment by lowaa** [comment]
Yep, it's done!

https://pypi.org/project/collapsing-thread-pool-executor/

Thanks for your patience

**Pull request merged**
