### PR TITLE
Eagerly shut down workers on workerpool shutdown when work queue is empty.

### PR DESCRIPTION
**Pull request by robertwb**
This fixes issue #3.

### CODE REVIEW

**Comment by robertwb** [comment]
@lowaa Could you please take a look at this?

**Comment by lowaa** [comment]
Approved, and thanks for the change. Sorry for the late response

**Comment by robertwb** [comment]
Thanks! Would it be possible to get another release out with this change?

**Comment by robertwb** [comment]
Ah, I see 2019.11 is already out. Thanks!

**Pull request merged**
